#!/bin/sh
remsh=ssh
prefix=`hostname`_
host=$1
shift
vars=$*
destvars=`echo "" $vars | sed -e 's/ / '$prefix'/g'`

#echo vars: $vars
#echo destvars: $destvars
bb_mmon $vars | $remsh $host bb_mnom $destvars
