#!/bin/sh
remsh_prog=ssh
prefix=`hostname`_
host=$1
shift
vars=$*
destvars=`echo "" $vars | sed -e 's/ / '$prefix'/g'`

#echo vars: $vars
#echo destvars: $destvars
$remsh $host bb_mmon $vars | bb_mnom $destvars
