#!/bin/sh
if [ $# -lt 1 ] ; then
   echo "need a var to transport the load into. "
   exit 1
fi
bb_set $1 `awk '{print $1}' /proc/loadavg`
if [ $# -gt 1 ] ; then 
   bb_set $2 `awk '{print $2}' /proc/loadavg`
fi   
if [ $# -gt 2 ] ; then 
   bb_set $3 `awk '{print $3}' /proc/loadavg`
fi   
