#!/bin/sh
configfile=$1
if [ -z $configfile ] ; then
  echo "Usage: $0 configfile"
  exit 1
fi
while read var interval file string ; do
  if echo $var | grep -q '^#' ; then
    #echo comment ignored
    echo -n ""
  elif [ -z $var ] ; then
    #echo empty line
    echo -n ""
  else
    #echo var=$var string=$string
    if echo $string | grep -q '^+' ; then
      #echo before string=$string
      string=`echo $string | sed -e 's/^+//'`
      #echo after string=$string
      plus="+";
    else
      plus="";
    fi
    if ! bb_print $var > /dev/null 2>&1 ; then
       echo creating $var
       bb_create $var float
    fi
    bb_procvar $var $file $string $plus $interval &
  fi
done < $configfile
